### PR TITLE
Improved cross-platform watching

### PR DESCRIPTION
**Pull request by kamsar**
NOTE: This was (intentionally) branched off #65 to avoid later conflicting. At this time this PR is here for discussion, not merging yet.

## Description
* Switch to a Gulp based watcher (for `npm run watch`)
* Analog of webpack-kicker.js, but using (a) webpack watch and (b) pure JS with no spawning
* Moved existing watch to `npm run watch-server` (not necessarily final)
* Improved webpack error reporting immensely by using correct APIs ;)

## Motivation and Context
This is needed to fix:
* That the watcher has no server-less mode
* That the watcher was totally borked on windows (#52)

## TODO:
* Once chokidar context is determined, get the watcher working fully and refactor the code appropriately
* Implement a server-based watch as well using a similar spawnless technique ([docs](https://webpack.github.io/docs/webpack-dev-server.html#api))
* Mess around with webpack-dev-server's proxy options to see if we can actually do HMR with Sitecore, which would be rad
* Remove `webpack-kicker.js`

## ??
I'm not sure what the use-case was for chokidar to restart webpack here. The kicker says (from @krambuhl):

```
// This is required because the webpack 
// static site generator plugin requires a 
// static list of paths
```
But the events are adding and deleting directories? What about adding individual files? Do we need to recycle the watcher essentially when any `.jsx` is touched?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by krambuhl** [comment]
This looks awesome, much better solution than calling the command line ugliness. I'll give this a pull today and check it out.

For context, the reason we are only looking for directory adds/removes is because we only need the directory to build a list of expected components.  This list is passed to the static site generator on webpack startup.  To update the list of components, webpack needs to be restarted.   Restarting webpack is a slow process (3-4s), and respawning on every file add is overkill, this seems like a happy medium.  

https://github.com/connectivedx/fuzzy-chainsaw/blob/develop/webpack.config.js#L13 is where the list of components is created, that algorythm should be updated to check directories instead of files. That will better align with the watcher.

**Comment by krambuhl** [comment]
Pulled upstream changes and pulled out watch and kicker code into build directory.

**Comment by krambuhl** [comment]
### There are a couple notes:

- you currently get a `Webpack completed without error.` message after each individual config is complete.  On my first build this tripped me up, because I thought the process had completed early.
- while watching with the dev server there is a console log `Bundle: INVALID` when the watchers trigger and `Bundle: VALID` when the resulting watches are complete.  This would be nice to keep if possible.

### And my concern:

While both of these methods work, on my machine I'm notice **huge** differences in performance between running webpack via gulp/node and using the cli commands.  

Command | Note | Execution Time
--- | --- | ---
`npm run build` | Gulp build | 29.750s
`npm run webpack-build` | Webpack cli build | 9.759s
`npm run watch` | Gulp watch, then new-tag, then cancel | 1m4.545s
`npm run webpack-watch` | Webpack watch, then new-tag, then cancel | 0m26.882s

**Comment by kamsar** [comment]
See #95 as to build scaling, not related to the watch code.

**Comment by kamsar** [comment]
As to the 'webpack completed' message - it can be removed but because webpack seems to only provide a callback after each configuration completes (and watch can trigger 1..n configurations) we have no way to realistically trigger 'success' after the watch event completes. Or we can look at maybe reducing the number of configurations ;)

**Comment by krambuhl** [comment]
It looks like a number of those messages were coming from webpack-dev-middleware that is being implemented by webpack-dev-server.  While this watch works, because it's using code.  it's missing a ton of features that are already built out by webpack-dev-server including a server, browser sync, hot module reloading and very good error messaging.  

There are improvements here that are worth merging, but I don't think this is the correct solution for watching.  We are making these changes because of cross platform differences in spawn, not because of a webpack-dev-server issue.  I would rather fix the spawn to work correctly and get the benefits of dev server than maintain our own watching method and error messaging.

**Comment by kamsar** [comment]
As I mentioned in passing earlier the webpack dev server has a similar API. It just need to be implemented against.

**Comment by krambuhl** [comment]
I'm confused by that ^, please explain 😄

**Comment by kamsar** [comment]
https://webpack.github.io/docs/webpack-dev-server.html#api

**Comment by krambuhl** [comment]
Can you please explain, these short responses are not helpful in providing context. and aggravating

**Comment by kamsar** [comment]
The same pattern being used to call webpack with watch through pure JS without a spawn can be used to also invoke `webpack-dev-server`, via the API that I linked to previously. Thus, instead of resorting to process spawning I am proposing investigating starting the dev server via the API instead of starting watch by itself.

**Comment by krambuhl** [comment]
Ahh, that sounds good. I didn't realize that you could use webpack-dev-server from code, I was under the impression it was a cli only tool.

**Comment by kamsar** [comment]
In which the `npm run watch` task now runs `webpack-dev-server` and should be just fine cross-platform.

The respawning mechanic is also present.

**Comment by krambuhl** [comment]
Merging in, this is great stuff. thanks for your effort making this more cross platform friendly.

**Pull request merged**
