### PR TITLE
Example page(s) optional developer notes

### PR DESCRIPTION
**Pull request by drolsen**
## Description
This now adds a new tab to the example page(s) tabbing system for developer notes.
Notes are tied to the examples under a component/composition's example file and is a new "devNotes" property.

## Motivation and Context
When a component or composition has a number of examples variations, we are only really ever given one chance to best describe the variation differences between each example. This new Notes tab/prop allows you to expand upon each example variation in greater detail, and keeps that note within context of the actual example variation instead of at the top in the readme.

## How Has This Been Tested?
builds work
new:component works
new:composition works
new:tag works

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bstaruk** [comment]
I really like this idea and it all works perfectly as-is!

I do have a couple suggestions/ideas though:

1. Perhaps we should only show the Notes tab in the styleguide example if notes are present, so it is more apparent to the visitor when an example has a note attached to it.

2. It'd be really neat if the notes field supported markdown. I may be overstepping the intended scope of this feature though.

I'd be happy to take a stab at implementing one or both of these features if everyone else thought they were good ideas.

**Comment by drolsen** [comment]
YES PLEASE!
I too was considering having these features, but went for KISS for first PR.
I've got no real markdown lib preferences over any others, so we might want to talk about what is being used before we merge this into dev. But yes, please add this under the same branch, commit and we will review once again.

Thanks Brian!

**Comment by CSKingMartin** [comment]
I like these changes very much. Perhaps we should throw in the usefulness of the current README presentation in this discussion as well?

The READMEs are super important and I heavily advocate using them. However as is (hidden on the page load) the READMEs don't exactly show their usefulness, where these 'Notes' tabs succeed in doing so.

**Comment by bstaruk** [comment]
I've gotten the conditional notes tab built and committed, but am having some difficulties coming up with a way to elegantly support markdown in the notes.

The challenge is that indentation & whitespace matters so much in markdown. For example, putting 4 spaces at the beginning of a line of markdown is how you create formatted code:

    this is text with 4 spaces before it

### The Challenge Demonstrated:

This is how we'd define an example `Header` tag using the current/initial implementation of the `devNotes` property:

```jsx
...
{
  name: 'default',
  devNotes: 'these are some test notes.',
  component: (
    <Heading>
      Hello
    </Heading>
  )
}
```

Now consider how we would actually format the `devNotes` property if it supported markdown, and that markdown was more than 1 line long.

There are two obvious solutions, but unfortunately neither of them are very pretty.

#### Option 1:

```jsx
const devNotesMd = `
# This is a header
This is some text

    this is some code

* this is a list item
* this is another list item
`;

...
{
  name: 'default',
  devNotes: devNotesMd,
  component: (
    <Heading>
      Hello
    </Heading>
  )
}
```

#### Option 2:

```jsx
...
{
  name: 'default',
  devNotes: `
# This is a header
This is some text

    this is some code

* this is a list item
* this is another list item
`,
  component: (
    <Heading>
      Hello
    </Heading>
  )
}
```

If anyone has any suggestions or feedback, I'd love to hear it, but for now I think that the current implementation of devNotes (a string that is put into a pre element) is sufficient. It's worth noting that the component/tag README.md file is visible on the SgExample page too, so there is a way to keep detailed notes.

**Comment by bstaruk** [comment]
I've gotten the conditional notes tab built and committed, but am having some difficulties coming up with a way to elegantly support markdown in the notes.

The challenge is that indentation & whitespace matters so much in markdown. For example, putting 4 spaces at the beginning of a line of markdown is how you create formatted code:

    # this is text with 4 spaces before it

### The Challenge Demonstrated:

This is how we'd define an example `Header` tag using the current/initial implementation of the `devNotes` property:

```jsx
...
{
  name: 'default',
  devNotes: 'these are some test notes.',
  component: (
    <Heading>
      Hello
    </Heading>
  )
}
```

Now consider how we would actually format the `devNotes` property if it supported markdown, and that markdown was more than 1 line long.

Keep in mind that the markdown cannot be indented, because if it is it'll just appear as code (like the first example in this note).

There are two obvious solutions, but unfortunately neither of them are very pretty.

#### Option 1:

```jsx
const devNotesMd = `
# This is a header
This is some text

    this is some code

* this is a list item
* this is another list item
`;

...
{
  name: 'default',
  devNotes: devNotesMd,
  component: (
    <Heading>
      Hello
    </Heading>
  )
}
```

#### Option 2:

```jsx
...
{
  name: 'default',
  devNotes: `
# This is a header
This is some text

    this is some code

* this is a list item
* this is another list item
`,
  component: (
    <Heading>
      Hello
    </Heading>
  )
}
```

If anyone has any suggestions or feedback, I'd love to hear it, but for now I think that the current implementation of devNotes (a string that is put into a pre element) is sufficient. It's worth noting that the component/tag README.md file is visible on the SgExample page too, so there is a way to keep detailed notes.

**Comment by drolsen** [comment]
We will leave this as a simple string for now.
Thanks Brian!

**Pull request merged**
