### PR TITLE
Configurable source and dest directories

### PR DESCRIPTION
**Pull request by krambuhl**
Adds directory information to package.json and replace hardcoded source and output directories with references. Take a look and let me know if this is enough, or if we need more fidelity.

### CODE REVIEW

**Comment by kamsar** [comment]
I suspect the location of the sneaky substring may be `RenderPage.jsx`:6:

`const path = locals.path.substr(0, locals.path.length - 5);`

**Comment by kamsar** [comment]
The build and clean are now working with alternate source and dist directories.

Still need to do something about preClean swatting a mosquito with a nuclear bomb before it eats me source code :)

**Comment by kamsar** [comment]
@krambuhl I figured out what I can do to adapt to the nuclear clean without requiring any alterations to FC and keeping things simple. Merge at will as long as I didn't break anything on your end either 😀

**Comment by krambuhl** [comment]
Made a small change related to an upstream change.  did a test of a output directory `../dist` and source directory change.

**Pull request merged**
