### PR TITLE
Tag table

### PR DESCRIPTION
**Pull request by pgregorova**
Wanted to create a tag table with a responsive table example that is purely CSS-based but does require some `data-heading` attributes. Maybe we could add another example that requires JS but doesn't require any HTML modification as it's done dynamically for us but we get the same result, as can be seen in this example of [responsive table](https://codepen.io/aardrian/pen/YEKmxP).

### CODE REVIEW

**Comment by bstaruk** [comment]
Looks great!! My only thought/suggestion is whether or not we should make sub-tags like `Table__data` (or `Table__cell`) and `Table__row` instead of just using `td` and `tr`.

This would allow us to change the css from `& td { ... }` to `&__data { ... }`.

This might be overkill though. Curious what the group thinks.

**Comment by CSKingMartin** [comment]
@bstaruk  -- Agreed! That is the intended structure! That way when we write CSS for these tags we can avoid targeting HTML default tags like `td` and `tr` outside of perhaps a reset.css.
@pgregorova -- one thing missing from your PR is documentation in the README.md file for this tag. Tables seem self-explanatory but it's helpful nonetheless to have consistent documentation.

**Comment by bstaruk** [comment]
I have added the following sub-tags under the main `Table` tag:

- Table__head
- Table__foot
- Table__body
- Table__row
- Table__header
- Table__data

I have also updated the example and CSS files under the `Table` tag to reflect these changes.

**Comment by pgregorova** [comment]
@CSKingMartin just added the documentation.

**Comment by drolsen** [comment]
Great work team!
Approved for development.

**Pull request merged**
