### PR TITLE
modifying build commands

### PR DESCRIPTION
**Pull request by bstaruk**
## Overview

In the current `master` branch, a `build:production` command is referenced in the description for the `full:production` command, but `build:production` does not exist.

To keep things consistent, and also resolve an issue we are facing internally with integrating Fuzzy Chainsaw with Legendary Pancake, I would like to propose the following changes:

1. Change `production` to `build:production` since all `production` does now is build the project with production parameters (minifying, etc).

2. Update `full:production` to use the new command (`build:production`) instead of the old (`production`).

3. Add a new `production` command which essentially does the same thing as `full:production` (runs `dll:production` & `build:production`).

We may want to remove `full:production` since it'll be a duplicate command (does the same thing as `production`) but I left it in because I do see value in having a `full:production` build to sit alongside `full:build`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by blipson89** [comment]
This will fix the LP Integration issue

**Comment by bstaruk** [comment]
@stoff & @elseloop Adding you as reviewers to get the ball rolling on this discussion.

Thanks!

**Comment by bstaruk** [comment]
Just pushed a minor version bump to this branch.

**Comment by bstaruk** [comment]
Updated PR base to be `develop` (not `master`).

**Comment by elseloop** [comment]
@drolsen @CSKingMartin @bstaruk Version changes should happen at the time of a release—that is, when `develop` is being merged into `master`—not when work from a single branch gets pulled into `develop`. The cumulative changes in each specific release will determine the scope of and therefore appropriate semver version needs.

**Pull request merged**
