### PR TITLE
updates files to pascal case

### PR DESCRIPTION
**Pull request by krambuhl**
Converts all files to pascal case and makes require pathing changes.

## Motivation and Context
In #70 we decided to use this file name style

## How Has This Been Tested?
I've run `npm run build` and `npm run watch` locally with success.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by kamsar** [comment]
image

**Comment by kamsar** [comment]
Suspect this may be due to some of the tags and other JSX files not being renamed with Pascal. But I could be wrong.

**Comment by krambuhl** [comment]
It's related to git not being base sensitive by default.  I had to change my git config on my local machine to [below], but it doesn't sync across repos..

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = false  ## <- change
	precomposeunicode = true
```

I think there is a more official way of doing this via `git mv` but will require a new PR.  I think I will do that...

**Comment by krambuhl** [comment]
Related: http://stackoverflow.com/a/8482021/1402494

**Comment by elseloop** [comment]
@krambuhl, was I understanding you correctly yesterday when we discussed this that these warnings will resolve themselves following this PR being merged since we’ll no longer be tracking both `component.jsx` and `Component.jsx`? Or do we need to explicitly remove the old files from git as well to avoid having to touch system configs?

**Comment by krambuhl** [comment]
I was under the impression they would rename themselves, but it looks like that's not the case.  When we rename a file, git records that as a new file and doesn't include a delete record... so I think the errors we are seeing are from webpack seeing 2 files with the same name `name.jsx` and `Name.jsx`.  @kamsar do you see 2 copies of files in your windows filesystem?

**Comment by kamsar** [comment]
No. But my understanding is that this is caused e.g. by 'require('foo.jsx') when the file is Foo.jsx on disk or the other way around.


________________________________

**Comment by elseloop** [comment]
I seemed to have misunderstood and thought these were git-related warnings and didn't realize these were _Webpack_ warnings. If remedying this is to clean up our `require()`s, then let's clean up our `require()`s. I can take a pass.

**Comment by krambuhl** [comment]
image

**Comment by krambuhl** [comment]
that should not be two sets of files.  renaming via the filesystem causes a git create without a corresponding git delete.  I will go through this again using the correct `git mv`.

**Comment by elseloop** [comment]
Wait. So _both_ casing versions _do_ exist? My filesystem does not mirror that. I'm confused.

inception

**Comment by krambuhl** [comment]
My lesson here appears to be, git filesystem != os filesystem

**Comment by krambuhl** [comment]
I should say, this only seems to be the case for changing the case of file names.

**Comment by elseloop** [comment]
All of the directory names remained lowercase locally for me after pulling in this branch. I think it might affect both directory and file names.

**Comment by krambuhl** [comment]
I am going to close this pull request and delete this branch, we should look at #81 for the correct fix.

**Pull request closed without merging**
